console.log("suma de dos numeros 13 + 7: ");
console.log(13 + 7);
console.log("suma de dos numeros 13 - 7: ");
console.log(13 - 7);
console.log("exprecion con parentesis (8*2 - 4 )/3: ");
//console.log("ejecucion se interrumpe");
console.log(13+7);
console.log("13"+"7");
console.log("13"+7);
console.log(+"13"+7);